let songs = [
  {
    name: "Dangote",
    path: "musics/Dangote.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Burna Boy 23",
    path: "musics/23.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "African-Giant",
    path: "musics/African-Giant.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Alarm-Clock",
    path: "musics/Alarm-Clock.mp3",
    artist: "Burna Boy",
    cover: "musics/Burna_Boy.png",
  },
  {
    name: "Another-Story",
    path: "musics/Another-Story.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Anybody",
    path: "musics/Anybody.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Bank-on-It",
    path: "musics/Burna-Boy-Bank-on-It-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Bebo",
    path: "musics/Burna-Boy-Bebo-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Blak-Ryno-Skit",
    path: "musics/Burna-Boy-Blak-Ryno-Skit.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Collateral-Damage",
    path: "musics/Burna-Boy-Collateral-Damage.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Comma",
    path: "musics/Burna-Boy-Comma-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Destiny",
    path: "musics/Burna-Boy-Destiny.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Anybody",
    path: "musics/Anybody.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Different",
    path: "musics/Burna-Boy-Different-feat-Damian-Marley-And-Angelique-Kidjo.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Gbona",
    path: "musics/Burna-Boy-Gbona.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Gum-Body",
    path: "musics/Burna-Boy-Gum-Body-feat-Jorja-Smith.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Killin-Dem",
    path: "musics/Burna-Boy-Killin-Dem-feat.-Zlatan.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Level-Up",
    path: "musics/Burna-Boy-Level-Up-Twice-As-Tall-ft-Youssou-N-Dour-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Monsters-You-Made",
    path: "musics/Burna-Boy-Monsters-You-Made-ft-Chris-Martin-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Naughty-by-Nature",
    path: "musics/Burna-Boy-Naughty-by-Nature-ft-Naughty-by-Nature-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "No-fit-Vex",
    path: "musics/Burna-Boy-No-fit-Vex-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Omo",
    path: "musics/Burna-Boy-Omo.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "On-The-Low",
    path: "musics/Burna-Boy-On-The-Low.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Onyeka-Baby",
    path: "musics/Burna-Boy-Onyeka-Baby-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Pull-Up",
    path: "musics/Burna-Boy-Pull-Up.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Real-Life",
    path: "musics/Burna-Boy-Real-Life-ft-Stormzy-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Secret",
    path: "musics/Burna-Boy-Secret-feat-Jeremih-And-Serani.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Show-Tell",
    path: "musics/Burna-Boy-Show-Tell-feat-Future.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Spiritual",
    path: "musics/Burna-Boy-Spiritual.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "This-Side",
    path: "musics/Burna-Boy-This-Side-feat-YG.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Time-Flies",
    path: "musics/Burna-Boy-Time-Flies-ft-Sauti-Sol-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Way-Too-Big",
    path: "musics/Burna-Boy-Way-Too-Big-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Wetin-Dey-Sup",
    path: "musics/Burna-Boy-Wetin-Dey-Sup-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Wetin-Man-Go-do",
    path: "musics/Burna-Boy-Wetin-Man-Go-do.mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
  {
    name: "Wonderful",
    path: "musics/Burna-Boy-Wonderful-(JustNaija.com).mp3",
    artist: "Burna Boy",
    cover: "images/Burna_Boy.png",
  },
];
